import { Inter as FontSans } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import { cn } from '@/lib/utils';
import { ToastContainer } from 'react-toastify';
import Loading from '@/app/loading';
import 'react-toastify/dist/ReactToastify.css';
import { Suspense } from 'react';
import Provider from '@/components/Provider';
import Auth from '@/components/Auth';
export const fontSans = FontSans({
    subsets: ['latin'],
    variable: '--font-sans',
});
export const metadata = {
    title: 'Komiho Admin',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <ClerkProvider
            appearance={{
                elements: {
                    footer: 'hidden',
                },
            }}>
            <html lang="en">
                <body
                    className={cn(
                        ' bg-background font-sans antialiased ',
                        fontSans.variable,
                    )}>
                    <ToastContainer />
                    <Provider>
                        <Auth>
                            <Suspense fallback={<Loading />}>
                                <div className="z-container">{children}</div>
                            </Suspense>
                        </Auth>
                    </Provider>
                </body>
            </html>
        </ClerkProvider>
    );
}
