export const listShirt = [
    'T-shirt',
    'Polo Shirt',
    'Sweater',
    'Tank Top',
    'Long-Sleeve Shirt',
    'Dress',
    'Jacket',
    "Women's Blouse",
    'Uniform Shirt',
    'Sports Jersey',
    'Denim Jacket',
    'Striped Shirt',
    "Men's Dress Shirt",
    'Round-Neck Shirt',
    'Floral Shirt',
    'Hoodie',
    'Windbreaker',
    'Winter Coat',
    'Traditional Vietnamese Dress',
];
export const listPants = [
    'Jeans',
    'Khaki Pants',
    'Shorts',
    'Cargo Shorts',
    'Dress Pants',
    'Jogger Pants',
    'Capri Pants',
    'Gym Shorts',
    'Windbreaker Pants',
    'Sport Pants',
    'Wide-Leg Pants',
    'Underwear',
    'Cowboy Pants',
    'Silk Pants',
    'Uniform Pants',
    'School Uniform Pants',
    'Chef Uniform Pants',
    'Police Uniform Pants',
    'Military Uniform Pants',
    'Medical Scrubs',
];
